<?php
require_once '../../config/database.php';

// Check if user is logged in and is admin
if (!isLoggedIn() || !isAdmin()) {
    sendResponse(false, 'Unauthorized access', null, 403);
}

if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    sendResponse(false, 'Invalid request method', null, 405);
}

$type = isset($_GET['type']) ? $_GET['type'] : 'reservasi';

// Get data
if ($type === 'reservasi') {
    $result = $conn->query("SELECT * FROM reservasi ORDER BY created_at DESC");
    $title = 'Laporan Reservasi';
    $filename = 'reservasi_report_' . date('Y-m-d_His') . '.pdf';
} else if ($type === 'berita') {
    $result = $conn->query("SELECT * FROM berita ORDER BY date DESC");
    $title = 'Laporan Berita';
    $filename = 'berita_report_' . date('Y-m-d_His') . '.pdf';
} else {
    sendResponse(false, 'Invalid type', null, 400);
}

$data = [];
while ($row = $result->fetch_assoc()) {
    $data[] = $row;
}

if (empty($data)) {
    sendResponse(false, 'No data to export', null, 400);
}

// Generate HTML for PDF
$html = '
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>' . $title . '</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { margin: 0; color: #1b742e; }
        .header p { margin: 5px 0; color: #666; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #1b742e; color: white; padding: 10px; text-align: left; border: 1px solid #ddd; }
        td { padding: 8px; border: 1px solid #ddd; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>' . $title . '</h1>
        <p>Taman Nasional Tesso Nilo</p>
        <p>Tanggal: ' . date('d-m-Y H:i:s') . '</p>
    </div>
    
    <table>
        <thead>
            <tr>';

// Add table headers
$headers = array_keys($data[0]);
foreach ($headers as $header) {
    $html .= '<th>' . htmlspecialchars($header) . '</th>';
}

$html .= '
            </tr>
        </thead>
        <tbody>';

// Add table data
foreach ($data as $row) {
    $html .= '<tr>';
    foreach ($row as $value) {
        $html .= '<td>' . htmlspecialchars($value) . '</td>';
    }
    $html .= '</tr>';
}

$html .= '
        </tbody>
    </table>
    
    <div class="footer">
        <p>Generated by Tesso Nilo System</p>
    </div>
</body>
</html>';

// For now, return as HTML with instruction to print as PDF
// In production, you would use a library like mPDF or TCPDF
header('Content-Type: text/html; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '.html"');
echo $html;
?>
